name: Node

on:
  release:
    types: ["published"]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2

    - run: "sudo apt-get update && sudo apt-get install binutils-aarch64-linux-gnu -y"

    - run: "sudo ./docker-linux.sh"
      working-directory: ./nuked-psg-node/scripts
    
    - run: "bash ./build-linux-x86.sh"
      working-directory: ./nuked-psg-node/scripts

    - run: "rm -rf ./target" 
    
    - run: "bash ./build-linux-x64.sh"
      working-directory: ./nuked-psg-node/scripts
    
    - run: "bash ./build-linux-arm64.sh"
      working-directory: ./nuked-psg-node/scripts

    - uses: softprops/action-gh-release@v1
      with:
        files: "./nuked-psg-node/prebuilds/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  

  win32:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2

    - run: "sudo ./docker-win32.sh"
      working-directory: ./nuked-psg-node/scripts
    
    - run: "bash ./build-win32-x86.sh"
      working-directory: ./nuked-psg-node/scripts
    - run: "bash ./build-win32-x64.sh"
      working-directory: ./nuked-psg-node/scripts

    - uses: softprops/action-gh-release@v1
      with:
        files: "./nuked-psg-node/prebuilds/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  win32-arm64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.3.0
      with:
        version: "11.0"
        directory: ${{ runner.temp }}/llvm

    - name: Set LIBCLANG_PATH
      run: echo "LIBCLANG_PATH=$((gcm clang).source -replace "clang.exe")" >> $env:GITHUB_ENV
    
    - run: "bash ./build-win32-arm64.sh"
      working-directory: ./nuked-psg-node/scripts

    - uses: softprops/action-gh-release@v1
      with:
        files: "./nuked-psg-node/prebuilds/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  darwin:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-node@v2
    
    - run: "bash ./build-darwin-x64.sh"
      working-directory: ./nuked-psg-node/scripts

    # - run: "bash ./build-darwin-arm64.sh"
    #   working-directory: ./nuked-psg-node/scripts

    - uses: softprops/action-gh-release@v1
      with:
        files: "./nuked-psg-node/prebuilds/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
